### ISSUE TITLE
Invariant Violation: dangerouslyRenderMarkup(...): on requiring this package and running tests

### ISSUE THREAD

**Issue by ryansukale** [yahoo/fluxible-immutable-utils#7] opened 2015-04-08 19:30 UTC
I get the following error when running tests that use a file that requires this package.
```
Invariant Violation: dangerouslyRenderMarkup(...): Cannot render markup in a worker thread. Make sure `window` and `document` are available globally before requiring React when unit testing or use React.renderToString for server rendering.
```

**Comment by dmhood** [comment] 2015-04-14 18:35
@ryansukale this is likely a problem with your test configuration.  See https://github.com/facebook/react/issues/2019

**Comment by edbo** [comment] 2015-06-20 07:14
I get this too if I do a clone and just try and run the test script `mocha tests --recursive --reporter spec --compilers js:babel/register`. Is it possible to share the magic you guys use to get those passing? It seems like the solution in that thread is somewhat heavy.

**Comment by 3den** [comment] 2015-06-23 00:28
@edbo this can be solved by just including what you need e.g. `require('fluxible-immutable-utils/lib/createImmutableStore')`

**Comment by 3den** [comment] 2015-06-23 00:29
i think this problem is caused by including react stuff on the tests that don't depend on react

**Comment by 3den** [comment] 2015-06-23 00:31
also for some reason  `js:babel/register` did not work for my jsx files, the solution was to call `require('jsx-test').jsxTranspile()` before the tests

**Comment by edbo** [comment] 2015-11-09 00:24
@3den I reckon you can close this out now. It doesn't occur in the main branch or on my branch anymore.

**Closed** 2015-11-09 22:38 UTC
Labels: bug
