### ISSUE TITLE
React dependency outdated

### ISSUE THREAD

**Issue by geekyme** [yahoo/fluxible-immutable-utils#31] opened 2015-10-13 10:37 UTC
This library breaks on react 0.14.0

```
npm ERR! peerinvalid Peer fluxible-immutable-utils@0.4.0 wants react@^0.13
```

**Comment by dmhood** [comment] 2015-10-14 20:20
Thanks, will be fixed with https://github.com/yahoo/fluxible-immutable-utils/pull/33

**Comment by dmhood** [comment] 2015-10-14 22:15
Re-opening since we are having some issues with our tests, will update before too long.

**Comment by dangw** [comment] 2015-10-30 23:56
any idea when this will be fixed?

**Closed** 2015-11-04 00:14 UTC

**Comment by akshayp** [comment] 2015-11-04 00:24
@dangw @geekyme Published 0.5.0 which will give you React 14 compatibility

**Comment by dangw** [comment] 2015-11-05 05:54
thanks!  confirmed it's working.
